version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
         name: Test
         command: ./docker-make test
     - run:
         name: Build
         command: ./docker-make all
