version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
         name: Test
         command: ./docker-make test
     - run:
         name: Build
         command: ./docker-make all
 publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_BUILD_NUM
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/out.bin
