version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Test
          command: ./docker-make test
      - run:
          name: Build
          command: ./docker-make all
      - persist_to_workspace:
          root: bin
          paths:
            - out.bin
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_BUILD_NUM
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/out.bin
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build   
      - publish-github-release:
          requires:
            - hold